/**
 * RV Nomad — Copyright (c) 2026 Kieran Woll Creative Works LLC
 * All Rights Reserved. Unauthorized copying or distribution is prohibited.
 * See LICENSE file for details.
 */

export interface BorderCrossing {
  id: string;
  name: string;
  canadianCity: string;
  canadianProvince: string;
  usCity: string;
  usState: string;
  /** true = open 24/7 */
  open24h: boolean;
  /** RV-friendly rating: 1-3 (1=tight/not ideal, 2=ok, 3=great for RVs) */
  rvFriendly: number;
  /** Typical wait time description */
  typicalWait: string;
  /** Notes specific to RVers */
  rvNotes: string;
  /** CBSA office phone (Canadian side) */
  cbsaPhone: string;
  /** CBP port phone (US side) — empty if not a staffed CBP port */
  cbpPhone: string;
  /** Latitude for map reference */
  lat: number;
  /** Longitude for map reference */
  lng: number;
  /** Region grouping */
  region: "Atlantic" | "Quebec" | "Ontario" | "Prairies" | "British Columbia" | "Alaska";
  /** Popularity rank (1 = busiest) */
  popularityRank: number;
  /** Whether this crossing has a dedicated RV/truck lane */
  hasRVLane: boolean;
}

export interface BorderLaw {
  id: string;
  rank: number;
  title: string;
  icon: string;
  severity: "critical" | "high" | "medium";
  /** Fine range or penalty description */
  penalty: string;
  description: string;
  /** Detailed tips for RVers */
  tips: string[];
  /** Which direction this applies: "entering_canada", "entering_us", "both" */
  direction: "entering_canada" | "entering_us" | "both";
}

export const BORDER_AGENCY_CONTACTS = {
  cbsa: {
    name: "Canada Border Services Agency (CBSA)",
    mainPhone: "1-800-461-9999",
    outsideCanada: "1-204-983-3500",
    borderInfoService: "1-800-959-2036",
    website: "https://www.cbsa-asfc.gc.ca",
    waitTimesUrl: "https://www.cbsa-asfc.gc.ca/bwt-taf/menu-eng.html",
    appName: "CanBorder",
    appUrl: "https://www.cbsa-asfc.gc.ca/travel-voyage/aps-app-eng.html",
  },
  cbp: {
    name: "U.S. Customs and Border Protection (CBP)",
    mainPhone: "1-877-227-5511",
    outsideUS: "+1-202-325-8000",
    website: "https://www.cbp.gov",
    waitTimesUrl: "https://bwt.cbp.gov",
  },
} as const;

export const BORDER_CROSSINGS: BorderCrossing[] = [
  // ── Atlantic Region ──
  {
    id: "st-stephen-ferry",
    name: "St. Stephen (Ferry Point Bridge)",
    canadianCity: "St. Stephen",
    canadianProvince: "NB",
    usCity: "Calais",
    usState: "ME",
    open24h: true,
    rvFriendly: 2,
    typicalWait: "5-15 min",
    rvNotes: "Smaller crossing, less traffic. Good for RVers heading to Maritime provinces.",
    cbsaPhone: "1-506-466-2363",
    cbpPhone: "1-207-454-3621",
    lat: 45.1917,
    lng: -67.2783,
    region: "Atlantic",
    popularityRank: 22,
    hasRVLane: false,
  },
  {
    id: "woodstock-houlton",
    name: "Woodstock Road (Houlton)",
    canadianCity: "Belleville",
    canadianProvince: "NB",
    usCity: "Houlton",
    usState: "ME",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "5-10 min",
    rvNotes: "Wide lanes, easy for large RVs. Gateway to New Brunswick and Trans-Canada Highway.",
    cbsaPhone: "1-506-325-3100",
    cbpPhone: "1-207-532-2131",
    lat: 46.1167,
    lng: -67.5833,
    region: "Atlantic",
    popularityRank: 20,
    hasRVLane: false,
  },
  {
    id: "edmundston",
    name: "Edmundston",
    canadianCity: "Edmundston",
    canadianProvince: "NB",
    usCity: "Madawaska",
    usState: "ME",
    open24h: true,
    rvFriendly: 2,
    typicalWait: "5-10 min",
    rvNotes: "Quiet crossing. Good access to northern New Brunswick and Quebec.",
    cbsaPhone: "1-506-739-0600",
    cbpPhone: "1-207-728-4376",
    lat: 47.3667,
    lng: -68.3167,
    region: "Atlantic",
    popularityRank: 24,
    hasRVLane: false,
  },

  // ── Quebec Region ──
  {
    id: "stanstead",
    name: "Stanstead (Highway 55)",
    canadianCity: "Stanstead",
    canadianProvince: "QC",
    usCity: "Derby Line",
    usState: "VT",
    open24h: true,
    rvFriendly: 2,
    typicalWait: "5-15 min",
    rvNotes: "Moderate traffic. Direct access to Eastern Townships and Montreal via Autoroute 55.",
    cbsaPhone: "1-819-876-2649",
    cbpPhone: "1-802-873-3219",
    lat: 45.0067,
    lng: -72.0983,
    region: "Quebec",
    popularityRank: 18,
    hasRVLane: false,
  },
  {
    id: "st-armand",
    name: "St-Armand / Philipsburg",
    canadianCity: "Saint-Armand",
    canadianProvince: "QC",
    usCity: "Highgate Springs",
    usState: "VT",
    open24h: true,
    rvFriendly: 2,
    typicalWait: "5-15 min",
    rvNotes: "Scenic route. Good for RVers heading to Montreal from Vermont/I-89.",
    cbsaPhone: "1-450-248-7316",
    cbpPhone: "1-802-868-2778",
    lat: 45.0167,
    lng: -73.0833,
    region: "Quebec",
    popularityRank: 16,
    hasRVLane: false,
  },
  {
    id: "lacolle-hwy15",
    name: "St-Bernard-de-Lacolle (Highway 15)",
    canadianCity: "Saint-Bernard-de-Lacolle",
    canadianProvince: "QC",
    usCity: "Champlain",
    usState: "NY",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "10-30 min",
    rvNotes: "Busiest Quebec crossing. Multi-lane highway. Under renovation until Winter 2027 — expect delays. RV-friendly lanes available.",
    cbsaPhone: "1-450-246-3545",
    cbpPhone: "1-518-298-8311",
    lat: 45.0033,
    lng: -73.4333,
    region: "Quebec",
    popularityRank: 5,
    hasRVLane: true,
  },

  // ── Ontario Region ──
  {
    id: "cornwall",
    name: "Cornwall (Seaway International Bridge)",
    canadianCity: "Cornwall",
    canadianProvince: "ON",
    usCity: "Massena",
    usState: "NY",
    open24h: true,
    rvFriendly: 2,
    typicalWait: "5-15 min",
    rvNotes: "Crosses through Akwesasne Mohawk territory. Two-stage inspection possible. Moderate RV traffic.",
    cbsaPhone: "1-613-932-3844",
    cbpPhone: "1-315-769-3091",
    lat: 45.0000,
    lng: -74.7500,
    region: "Ontario",
    popularityRank: 15,
    hasRVLane: false,
  },
  {
    id: "thousand-islands",
    name: "Lansdowne (Thousand Islands Bridge)",
    canadianCity: "Lansdowne",
    canadianProvince: "ON",
    usCity: "Alexandria Bay",
    usState: "NY",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "5-20 min",
    rvNotes: "Scenic bridge crossing. Popular with RVers visiting Thousand Islands region. Wide lanes accommodate large rigs.",
    cbsaPhone: "1-613-659-3644",
    cbpPhone: "1-315-482-2681",
    lat: 44.3667,
    lng: -76.0833,
    region: "Ontario",
    popularityRank: 12,
    hasRVLane: false,
  },
  {
    id: "queenston-lewiston",
    name: "Queenston-Lewiston Bridge",
    canadianCity: "Niagara-on-the-Lake",
    canadianProvince: "ON",
    usCity: "Lewiston",
    usState: "NY",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "10-25 min",
    rvNotes: "Best Niagara crossing for RVs — has dedicated truck/RV lanes. Less congested than Rainbow Bridge. Direct access to QEW highway.",
    cbsaPhone: "1-905-262-5321",
    cbpPhone: "1-716-754-4596",
    lat: 43.1617,
    lng: -79.0483,
    region: "Ontario",
    popularityRank: 4,
    hasRVLane: true,
  },
  {
    id: "rainbow-bridge",
    name: "Niagara Falls (Rainbow Bridge)",
    canadianCity: "Niagara Falls",
    canadianProvince: "ON",
    usCity: "Niagara Falls",
    usState: "NY",
    open24h: true,
    rvFriendly: 1,
    typicalWait: "10-30 min",
    rvNotes: "NOT recommended for large RVs. Passenger vehicles only — no commercial trucks. Tight turns and narrow lanes. Use Queenston-Lewiston or Peace Bridge instead.",
    cbsaPhone: "1-905-354-4424",
    cbpPhone: "1-716-282-2224",
    lat: 43.0900,
    lng: -79.0700,
    region: "Ontario",
    popularityRank: 6,
    hasRVLane: false,
  },
  {
    id: "peace-bridge",
    name: "Fort Erie (Peace Bridge)",
    canadianCity: "Fort Erie",
    canadianProvince: "ON",
    usCity: "Buffalo",
    usState: "NY",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "15-45 min",
    rvNotes: "Very busy crossing. Has dedicated truck/RV lanes. Connects directly to I-190 (US) and QEW (Canada). Allow extra time on weekends and holidays.",
    cbsaPhone: "1-905-994-6354",
    cbpPhone: "1-716-885-3914",
    lat: 42.9067,
    lng: -78.9050,
    region: "Ontario",
    popularityRank: 2,
    hasRVLane: true,
  },
  {
    id: "blue-water-bridge",
    name: "Sarnia (Blue Water Bridge)",
    canadianCity: "Point Edward",
    canadianProvince: "ON",
    usCity: "Port Huron",
    usState: "MI",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "10-30 min",
    rvNotes: "Major crossing for RVers heading to/from Michigan. Twin span bridge with good RV clearance. Connects to I-94 (US) and Highway 402 (Canada).",
    cbsaPhone: "1-519-344-5561",
    cbpPhone: "1-810-985-9541",
    lat: 42.9983,
    lng: -82.4217,
    region: "Ontario",
    popularityRank: 3,
    hasRVLane: true,
  },
  {
    id: "ambassador-bridge",
    name: "Ambassador Bridge",
    canadianCity: "Windsor",
    canadianProvince: "ON",
    usCity: "Detroit",
    usState: "MI",
    open24h: true,
    rvFriendly: 2,
    typicalWait: "15-45 min",
    rvNotes: "Busiest US-Canada crossing. Heavy commercial traffic. RVs allowed but can be slow. Consider Detroit-Windsor Tunnel for smaller rigs or Blue Water Bridge as alternative.",
    cbsaPhone: "1-519-257-6400",
    cbpPhone: "1-313-226-3141",
    lat: 42.3117,
    lng: -83.0733,
    region: "Ontario",
    popularityRank: 1,
    hasRVLane: true,
  },
  {
    id: "detroit-windsor-tunnel",
    name: "Detroit-Windsor Tunnel",
    canadianCity: "Windsor",
    canadianProvince: "ON",
    usCity: "Detroit",
    usState: "MI",
    open24h: true,
    rvFriendly: 1,
    typicalWait: "10-25 min",
    rvNotes: "NOT suitable for large RVs. Height restriction: 12'2\" (3.7m). No propane/flammable cargo allowed in tunnel. Use Ambassador Bridge or Blue Water Bridge instead.",
    cbsaPhone: "1-519-257-6400",
    cbpPhone: "1-313-226-3141",
    lat: 42.3233,
    lng: -83.0400,
    region: "Ontario",
    popularityRank: 7,
    hasRVLane: false,
  },
  {
    id: "sault-ste-marie",
    name: "Sault Ste. Marie (International Bridge)",
    canadianCity: "Sault Ste. Marie",
    canadianProvince: "ON",
    usCity: "Sault Ste. Marie",
    usState: "MI",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "5-15 min",
    rvNotes: "Good RV crossing. Gateway to northern Ontario and Trans-Canada Highway. Moderate traffic. Wide lanes.",
    cbsaPhone: "1-705-941-3120",
    cbpPhone: "1-906-632-2631",
    lat: 46.5100,
    lng: -84.3500,
    region: "Ontario",
    popularityRank: 11,
    hasRVLane: false,
  },
  {
    id: "fort-frances",
    name: "Fort Frances (International Falls Bridge)",
    canadianCity: "Fort Frances",
    canadianProvince: "ON",
    usCity: "International Falls",
    usState: "MN",
    open24h: true,
    rvFriendly: 2,
    typicalWait: "5-10 min",
    rvNotes: "Quiet crossing. Gateway to Voyageurs National Park area. Low traffic makes it easy for RVs.",
    cbsaPhone: "1-807-274-3655",
    cbpPhone: "1-218-283-2541",
    lat: 48.6017,
    lng: -93.4017,
    region: "Ontario",
    popularityRank: 19,
    hasRVLane: false,
  },

  // ── Prairies Region ──
  {
    id: "emerson-pembina",
    name: "Emerson (Pembina)",
    canadianCity: "Emerson",
    canadianProvince: "MB",
    usCity: "Pembina",
    usState: "ND",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "5-15 min",
    rvNotes: "Major prairie crossing on I-29/Highway 75. Easy for large RVs. Gateway to Winnipeg and western Canada.",
    cbsaPhone: "1-204-373-2681",
    cbpPhone: "1-701-825-6551",
    lat: 49.0000,
    lng: -97.2167,
    region: "Prairies",
    popularityRank: 10,
    hasRVLane: false,
  },
  {
    id: "north-portal",
    name: "North Portal (Portal)",
    canadianCity: "North Portal",
    canadianProvince: "SK",
    usCity: "Portal",
    usState: "ND",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "5-10 min",
    rvNotes: "Quiet crossing on US-52/Highway 39. Easy for RVs. Gateway to Saskatchewan and Regina.",
    cbsaPhone: "1-306-927-4400",
    cbpPhone: "1-701-926-4611",
    lat: 49.0000,
    lng: -102.5500,
    region: "Prairies",
    popularityRank: 17,
    hasRVLane: false,
  },
  {
    id: "coutts-sweetgrass",
    name: "Coutts (Sweetgrass)",
    canadianCity: "Coutts",
    canadianProvince: "AB",
    usCity: "Sweetgrass",
    usState: "MT",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "5-15 min",
    rvNotes: "Major crossing on I-15/Highway 4. Popular with RVers heading to Banff, Calgary, and the Canadian Rockies. Wide lanes, easy for big rigs.",
    cbsaPhone: "1-403-344-3766",
    cbpPhone: "1-406-335-2611",
    lat: 49.0000,
    lng: -111.9667,
    region: "Prairies",
    popularityRank: 9,
    hasRVLane: false,
  },

  // ── British Columbia Region ──
  {
    id: "pacific-highway",
    name: "Pacific Highway (Peace Arch)",
    canadianCity: "Surrey",
    canadianProvince: "BC",
    usCity: "Blaine",
    usState: "WA",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "15-45 min",
    rvNotes: "Busiest BC crossing. Multi-lane with NEXUS lanes. Can be very busy on weekends. Connects I-5 to Highway 99. Good for RVs but allow extra time.",
    cbsaPhone: "1-604-535-9754",
    cbpPhone: "1-360-332-8511",
    lat: 49.0017,
    lng: -122.7567,
    region: "British Columbia",
    popularityRank: 8,
    hasRVLane: true,
  },
  {
    id: "douglas",
    name: "Douglas (Peace Arch)",
    canadianCity: "Surrey",
    canadianProvince: "BC",
    usCity: "Blaine",
    usState: "WA",
    open24h: true,
    rvFriendly: 2,
    typicalWait: "15-40 min",
    rvNotes: "Passenger vehicles only — no commercial. Adjacent to Peace Arch Park. Can be busy on weekends. Good alternative to Pacific Highway for smaller RVs.",
    cbsaPhone: "1-604-535-9754",
    cbpPhone: "1-360-332-8511",
    lat: 49.0017,
    lng: -122.7583,
    region: "British Columbia",
    popularityRank: 13,
    hasRVLane: false,
  },
  {
    id: "aldergrove",
    name: "Aldergrove (Lynden)",
    canadianCity: "Aldergrove",
    canadianProvince: "BC",
    usCity: "Lynden",
    usState: "WA",
    open24h: false,
    rvFriendly: 2,
    typicalWait: "5-20 min",
    rvNotes: "Less busy alternative to Pacific Highway. Not 24 hours — check hours before traveling. Good for RVers wanting to avoid Surrey/Blaine congestion.",
    cbsaPhone: "1-604-857-6438",
    cbpPhone: "1-360-354-2423",
    lat: 49.0000,
    lng: -122.4833,
    region: "British Columbia",
    popularityRank: 14,
    hasRVLane: false,
  },
  {
    id: "abbotsford-huntingdon",
    name: "Abbotsford-Huntingdon (Sumas)",
    canadianCity: "Huntingdon",
    canadianProvince: "BC",
    usCity: "Sumas",
    usState: "WA",
    open24h: true,
    rvFriendly: 2,
    typicalWait: "5-20 min",
    rvNotes: "Good alternative to Pacific Highway. Connects to Trans-Canada Highway east. Moderate RV traffic.",
    cbsaPhone: "1-604-850-6413",
    cbpPhone: "1-360-988-2971",
    lat: 49.0000,
    lng: -122.2667,
    region: "British Columbia",
    popularityRank: 15,
    hasRVLane: false,
  },
  {
    id: "roosville",
    name: "Roosville (Eureka)",
    canadianCity: "Roosville",
    canadianProvince: "BC",
    usCity: "Eureka",
    usState: "MT",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "5-10 min",
    rvNotes: "Scenic Rocky Mountain crossing on US-93/Highway 93. Popular with RVers doing Glacier NP to Canadian Rockies route. Very low traffic, easy for big rigs.",
    cbsaPhone: "1-250-887-3413",
    cbpPhone: "1-406-889-3865",
    lat: 49.0000,
    lng: -115.0667,
    region: "British Columbia",
    popularityRank: 21,
    hasRVLane: false,
  },
  {
    id: "kingsgate",
    name: "Kingsgate (Eastport)",
    canadianCity: "Kingsgate",
    canadianProvince: "BC",
    usCity: "Eastport",
    usState: "ID",
    open24h: true,
    rvFriendly: 3,
    typicalWait: "5-10 min",
    rvNotes: "Quiet crossing on US-95/Highway 95. Good for RVers heading to Kootenay region. Very low traffic.",
    cbsaPhone: "1-250-424-5313",
    cbpPhone: "1-208-267-3966",
    lat: 49.0000,
    lng: -116.1833,
    region: "British Columbia",
    popularityRank: 23,
    hasRVLane: false,
  },

  // ── Alaska Region ──
  {
    id: "alcan-beaver-creek",
    name: "Alcan / Beaver Creek (Alaska Highway)",
    canadianCity: "Beaver Creek",
    canadianProvince: "YT",
    usCity: "Tok (via Alaska Hwy)",
    usState: "AK",
    open24h: false,
    rvFriendly: 3,
    typicalWait: "5-15 min",
    rvNotes: "The main Alaska Highway crossing. Essential for RVers driving to/from Alaska. Open limited hours — check before traveling. Remote location, fuel up beforehand.",
    cbsaPhone: "1-867-862-7230",
    cbpPhone: "1-907-774-2252",
    lat: 62.6500,
    lng: -141.0000,
    region: "Alaska",
    popularityRank: 25,
    hasRVLane: false,
  },
  {
    id: "hyder-stewart",
    name: "Hyder / Stewart",
    canadianCity: "Stewart",
    canadianProvince: "BC",
    usCity: "Hyder",
    usState: "AK",
    open24h: false,
    rvFriendly: 2,
    typicalWait: "5 min",
    rvNotes: "Tiny, remote crossing. Popular for bear viewing at Fish Creek. No US customs station — honor system entering Hyder. Canadian customs on return.",
    cbsaPhone: "1-250-636-2564",
    cbpPhone: "",
    lat: 55.9167,
    lng: -130.0167,
    region: "Alaska",
    popularityRank: 28,
    hasRVLane: false,
  },
  {
    id: "poker-creek",
    name: "Poker Creek / Little Gold Creek",
    canadianCity: "Little Gold Creek",
    canadianProvince: "YT",
    usCity: "Poker Creek",
    usState: "AK",
    open24h: false,
    rvFriendly: 2,
    typicalWait: "5 min",
    rvNotes: "Remote crossing on Top of the World Highway. Seasonal — typically open mid-May to mid-September. Gravel road, suitable for smaller RVs. Spectacular scenery.",
    cbsaPhone: "1-867-862-7230",
    cbpPhone: "1-907-774-2252",
    lat: 64.0500,
    lng: -141.0000,
    region: "Alaska",
    popularityRank: 29,
    hasRVLane: false,
  },
];

export const BORDER_LAWS: BorderLaw[] = [
  {
    id: "firearms",
    rank: 1,
    title: "Undeclared Firearms",
    icon: "gpp-bad",
    severity: "critical",
    penalty: "Seizure of weapon, fines up to $50,000 CAD, possible imprisonment",
    description: "Canada has zero-tolerance for undeclared firearms. US concealed carry permits are NOT recognized in Canada. Even forgetting a handgun in your RV's glove box can result in criminal charges.",
    tips: [
      "Search your entire RV thoroughly before crossing — check glove boxes, drawers, under seats",
      "US concealed carry permits have NO validity in Canada",
      "Non-restricted firearms (most rifles/shotguns) can be brought in with a declaration form and $25 CAD fee",
      "Handguns are 'restricted' in Canada and require special authorization — apply 3+ months in advance",
      "Ammunition must be declared separately",
      "Pepper spray for personal protection is PROHIBITED in Canada (bear spray is allowed for wilderness use)",
    ],
    direction: "entering_canada",
  },
  {
    id: "cannabis",
    rank: 2,
    title: "Cannabis / Marijuana",
    icon: "block",
    severity: "critical",
    penalty: "Criminal charges, fines up to $5,000+, imprisonment up to 14 years",
    description: "Despite cannabis being legal in both countries, transporting it across the border in either direction is a serious federal criminal offense. This includes edibles, oils, vape cartridges, and even trace amounts.",
    tips: [
      "Remove ALL cannabis products from your RV before crossing in either direction",
      "This includes edibles, oils, tinctures, vape cartridges, and paraphernalia",
      "Even CBD products can cause issues — leave them behind",
      "Admitting past cannabis use can result in being denied entry to the US",
      "Don't joke about cannabis with border agents",
    ],
    direction: "both",
  },
  {
    id: "food-agriculture",
    rank: 3,
    title: "Undeclared Food & Agricultural Products",
    icon: "no-food",
    severity: "high",
    penalty: "$500-$1,300 CAD per violation; seizure of goods",
    description: "Both countries strictly regulate food imports to prevent disease and invasive species. RVers commonly forget about food in their fridges and pantries. You MUST declare all food items — even if they're allowed.",
    tips: [
      "Declare ALL food, even items you think are allowed — failure to declare is the violation",
      "Prohibited into Canada: most fresh meat, dairy, eggs, poultry products",
      "Prohibited into US: most meat, poultry, fresh fruits and vegetables from Canada",
      "Clean out your RV fridge and pantry before crossing — easier than sorting what's allowed",
      "Canned and commercially packaged foods are generally OK in both directions",
      "Firewood is PROHIBITED into Canada (invasive insect risk) — buy locally",
    ],
    direction: "both",
  },
  {
    id: "alcohol-tobacco",
    rank: 4,
    title: "Exceeding Alcohol & Tobacco Limits",
    icon: "liquor",
    severity: "medium",
    penalty: "Duty charges on excess; seizure if undeclared",
    description: "Both countries have duty-free limits on alcohol and tobacco. RVers often have more than the limit stashed in their rigs. You can bring more than the limit, but you must declare it and pay duty.",
    tips: [
      "Canada duty-free: 1.5L wine OR 1.14L spirits OR 8.5L (about 24 cans) beer per adult",
      "US duty-free: 1L alcohol per adult (21+)",
      "You CAN bring more — just declare it and pay the duty/tax",
      "Tobacco: Canada allows 200 cigarettes and 50 cigars duty-free",
      "Tobacco: US allows 200 cigarettes and 100 cigars duty-free",
      "Always declare — penalties for hiding are far worse than the duty",
    ],
    direction: "both",
  },
  {
    id: "children-consent",
    rank: 5,
    title: "Traveling with Minors Without Consent",
    icon: "family-restroom",
    severity: "high",
    penalty: "Denied entry, potential investigation, child welfare involvement",
    description: "If traveling with children who are not your own (including grandchildren), or if you're a separated/divorced parent, you need written consent from the other parent(s). This is strictly enforced to prevent child abduction.",
    tips: [
      "Carry a notarized consent letter from ALL parents/guardians not traveling",
      "Include: child's name, DOB, traveling adult's info, trip dates, destination, parent contact info",
      "Divorced/separated parents: bring custody documents AND consent from other parent",
      "Grandparents: always carry consent letters even for short trips",
      "Include authorization for emergency medical treatment for each child",
      "Both Canada and US enforce this — applies in both directions",
    ],
    direction: "both",
  },
  {
    id: "documentation",
    rank: 6,
    title: "Expired or Insufficient ID Documents",
    icon: "badge",
    severity: "high",
    penalty: "Denied entry",
    description: "A valid passport is required for crossing the US-Canada border. Enhanced driver's licenses (EDL) are accepted at land crossings in some states/provinces. REAL ID alone is NOT sufficient for international travel.",
    tips: [
      "Valid passport is the safest document — accepted everywhere",
      "Enhanced Driver's License (EDL) accepted at land crossings only (not air)",
      "REAL ID is NOT valid for crossing into Canada or returning to the US",
      "NEXUS card speeds up crossing and serves as ID — highly recommended for frequent crossers",
      "Check passport expiration — some agents may question passports expiring within 6 months",
      "Carry RV registration, insurance proof, and pet vaccination records",
    ],
    direction: "both",
  },
  {
    id: "vehicle-soil",
    rank: 7,
    title: "Dirty/Contaminated Vehicle",
    icon: "cleaning-services",
    severity: "medium",
    penalty: "Refused entry until vehicle is cleaned",
    description: "Canada can refuse entry to vehicles contaminated with excessive soil or mud, to prevent the spread of invasive species and plant diseases. This is especially relevant for RVers who've been boondocking or off-roading.",
    tips: [
      "Wash your RV undercarriage and wheel wells before crossing into Canada",
      "Remove all visible soil, mud, and plant material",
      "Clean camping gear, hiking boots, and outdoor equipment",
      "Drain and clean any water tanks that may contain non-native organisms",
      "This is particularly enforced during agricultural inspection seasons",
    ],
    direction: "entering_canada",
  },
  {
    id: "overstay",
    rank: 8,
    title: "Exceeding Permitted Stay Duration",
    icon: "schedule",
    severity: "high",
    penalty: "Deportation, future entry bans, fines",
    description: "US visitors to Canada and Canadian visitors to the US are typically allowed to stay up to 6 months. Snowbirds and full-time RVers sometimes lose track of time. Overstaying can result in deportation and difficulty entering in the future.",
    tips: [
      "Standard visitor stay: up to 6 months in both countries",
      "Keep track of your entry date — border agents may ask",
      "If you need to stay longer, apply for an extension BEFORE your time expires",
      "Canada: apply to IRCC for visitor record extension",
      "US: file Form I-539 with USCIS for extension",
      "Snowbirds: the 182-day rule applies to tax residency — track carefully",
    ],
    direction: "both",
  },
  {
    id: "undeclared-purchases",
    rank: 9,
    title: "Undeclared Purchases Over Exemption",
    icon: "shopping-cart",
    severity: "medium",
    penalty: "25-70% of value of seized goods; vehicle seizure possible",
    description: "When returning to your home country, you must declare all purchases made abroad. Both countries have duty-free personal exemptions based on time spent abroad. RVers who shop across the border often exceed limits.",
    tips: [
      "Canada: $200 CAD exemption for 24-48 hour trips, $800 CAD for 7+ days",
      "US: $800 USD exemption for 48+ hour trips",
      "Keep all receipts organized — agents may ask for proof of value",
      "Declare everything — even if over the limit, you just pay duty on the excess",
      "Hiding purchases can result in seizure of ALL goods plus your vehicle",
      "CBSA keeps infraction records — repeat offenders face stricter screening",
    ],
    direction: "both",
  },
  {
    id: "prescription-meds",
    rank: 10,
    title: "Prescription Medications Without Documentation",
    icon: "medication",
    severity: "high",
    penalty: "Seizure of medications, potential criminal charges",
    description: "Prescription medications must be in original pharmacy containers with your name on the label. Some US medications are controlled substances in Canada and vice versa. RVers on multiple medications need to be especially careful.",
    tips: [
      "Keep ALL medications in original pharmacy-labeled containers",
      "Carry a letter from your doctor listing medications and dosages",
      "Some common US medications (e.g., certain pain meds, stimulants) are controlled in Canada",
      "Bring only the amount you'll need for your trip — large quantities raise flags",
      "Medical marijuana cards are NOT valid across the border",
      "Declare medications if asked — don't hide them",
    ],
    direction: "both",
  },
];

/** Get crossings filtered by region */
export function getCrossingsByRegion(region: BorderCrossing["region"]): BorderCrossing[] {
  return BORDER_CROSSINGS.filter((c) => c.region === region);
}

/** Get the top N most popular crossings */
export function getTopCrossings(n: number = 10): BorderCrossing[] {
  return [...BORDER_CROSSINGS].sort((a, b) => a.popularityRank - b.popularityRank).slice(0, n);
}

/** Get RV-friendly crossings (rating 3) */
export function getRVFriendlyCrossings(): BorderCrossing[] {
  return BORDER_CROSSINGS.filter((c) => c.rvFriendly === 3);
}

/** All unique regions */
export const BORDER_REGIONS: BorderCrossing["region"][] = [
  "Atlantic",
  "Quebec",
  "Ontario",
  "Prairies",
  "British Columbia",
  "Alaska",
];
