// Track Chair Finder - States and parks offering all-terrain wheelchairs for disabled hikers
// Data sourced from thetrackchair.com/finder, state park websites, NPS, and Ford Bronco Wild Fund

export interface TrackChairLocation {
  id: string;
  parkName: string;
  state: string;
  stateCode: string;
  region?: string; // e.g. "West TN", "East TN"
  latitude: number;
  longitude: number;
  address?: string;
  phone: string;
  email?: string;
  website?: string;
  reservationUrl?: string;
  chairCount: number;
  chairType: string; // "Action Trackchair", "GRIT Freedom Chair", etc.
  cost: string; // "Free", "$25/day", etc.
  reservationMethod: string; // "Call ahead", "Online", "Walk-in"
  advanceNotice: string; // "24 hours", "48 hours", etc.
  maxDuration: string; // "2 hours", "3 hours", "Full day"
  availability: string; // "Year-round", "May-Oct", etc.
  terrainTypes: string[]; // "trails", "beach", "snow", "campground"
  accessibleTrails?: string[]; // specific trail names
  notes?: string;
  mapUrl: string;
}

export interface TrackChairState {
  stateCode: string;
  stateName: string;
  programName?: string;
  programWebsite?: string;
  totalLocations: number;
  totalChairs: number;
  highlights: string;
}

export const TRACK_CHAIR_STATES: TrackChairState[] = [
  {
    stateCode: "MN",
    stateName: "Minnesota",
    programName: "MN State Parks Track Chair Program",
    programWebsite: "https://www.dnr.state.mn.us/state_parks/track-chairs.html",
    totalLocations: 17,
    totalChairs: 17,
    highlights: "Largest state park track chair program in the US. 13+ state parks plus zoos and nature centers. All free, reserve online.",
  },
  {
    stateCode: "TN",
    stateName: "Tennessee",
    programName: "TN State Parks All-Terrain Wheelchairs",
    programWebsite: "https://tnstateparks.com/accessibility/all-terrain-wheelchairs",
    totalLocations: 32,
    totalChairs: 32,
    highlights: "Most parks with track chairs of any state (32). Covers West, Middle, and East TN. All free, reserve online.",
  },
  {
    stateCode: "MI",
    stateName: "Michigan",
    programName: "MI DNR Track Chair Program",
    programWebsite: "https://www.michigan.gov/dnr/about/accessibility/track-chairs",
    totalLocations: 32,
    totalChairs: 35,
    highlights: "32 state parks and recreation areas. Beach, trail, and campground access. All free, call 24hrs ahead.",
  },
  {
    stateCode: "GA",
    stateName: "Georgia",
    programName: "All-Terrain Georgia (Aimee Copeland Foundation)",
    programWebsite: "https://www.allterraingeorgia.org/",
    totalLocations: 17,
    totalChairs: 17,
    highlights: "Partnership with Aimee Copeland Foundation. Free certification required. 17 state parks and historic sites.",
  },
  {
    stateCode: "LA",
    stateName: "Louisiana",
    programName: "LA State Parks Track Chair Program",
    programWebsite: "https://www.lastateparks.com",
    totalLocations: 7,
    totalChairs: 7,
    highlights: "7 state parks across Louisiana. All free, reserve online through state parks website.",
  },
  {
    stateCode: "MO",
    stateName: "Missouri",
    programName: "MO State Parks Track Chair Program",
    programWebsite: "https://mostateparks.com/track-chair",
    totalLocations: 6,
    totalChairs: 6,
    highlights: "6 state parks. Donated by Missouri Parks Association. Free, companion required.",
  },
  {
    stateCode: "TX",
    stateName: "Texas",
    programName: "TPWD Assistive Chairs Program",
    programWebsite: "https://tpwd.texas.gov/state-parks/park-information/accessibility/assistive-chairs",
    totalLocations: 10,
    totalChairs: 10,
    highlights: "10 state parks across Texas. Launched 2025. Free, contact park to reserve.",
  },
  {
    stateCode: "SD",
    stateName: "South Dakota",
    programName: "SD Game, Fish & Parks",
    totalLocations: 3,
    totalChairs: 3,
    highlights: "Custer State Park plus two Outdoor Campus locations. Free to use.",
  },
  {
    stateCode: "ND",
    stateName: "North Dakota",
    programName: "ND Parks and Recreation",
    totalLocations: 4,
    totalChairs: 4,
    highlights: "State parks and Game & Fish Department. Free, call ahead.",
  },
  {
    stateCode: "CO",
    stateName: "Colorado",
    programName: "CO Parks & Wildlife Track Chair Program",
    programWebsite: "https://cpw.state.co.us",
    totalLocations: 3,
    totalChairs: 3,
    highlights: "Started at Staunton State Park, expanding. Free, reserve via email.",
  },
  {
    stateCode: "WI",
    stateName: "Wisconsin",
    programName: "Peninsula State Park Friends",
    programWebsite: "https://peninsulastatepark.org/reserve-our-track-chair/",
    totalLocations: 2,
    totalChairs: 2,
    highlights: "Peninsula State Park (Door County) and others. Free, reserve online.",
  },
  {
    stateCode: "NC",
    stateName: "North Carolina",
    programName: "NC Wildlife Resources Commission Trackchair Program",
    programWebsite: "https://www.ncwildlife.gov/outdoors/accessible-opportunities/trackchair-program",
    totalLocations: 5,
    totalChairs: 5,
    highlights: "Available at game lands and wildlife areas. Free for hunting, fishing, birding.",
  },
  {
    stateCode: "WA",
    stateName: "Washington",
    programName: "WA State Parks",
    totalLocations: 2,
    totalChairs: 2,
    highlights: "Lake Sammamish and Riverside State Parks. Seasonal rotation program.",
  },
  {
    stateCode: "MT",
    stateName: "Montana",
    programName: "MT Fish, Wildlife & Parks",
    totalLocations: 1,
    totalChairs: 1,
    highlights: "Lake Elmo State Park near Billings. Free, call ahead.",
  },
  {
    stateCode: "WY",
    stateName: "Wyoming",
    programName: "Ford Bronco Wild Fund Grant",
    totalLocations: 1,
    totalChairs: 1,
    highlights: "Bear River State Park. Funded by Ford Bronco Wild Fund grant.",
  },
  {
    stateCode: "CT",
    stateName: "Connecticut",
    programName: "The Nature Conservancy",
    totalLocations: 1,
    totalChairs: 1,
    highlights: "TNC preserves. New 2025 program. Reserve online.",
  },
  {
    stateCode: "OH",
    stateName: "Ohio",
    programName: "Metroparks & Cleveland Metroparks",
    totalLocations: 2,
    totalChairs: 3,
    highlights: "Metroparks Toledo (Oak Openings) and Cleveland Metroparks. Free via Reeve Foundation Grant.",
  },
];

export const TRACK_CHAIR_LOCATIONS: TrackChairLocation[] = [
  // ===== MINNESOTA (17 locations) =====
  {
    id: "mn-camden",
    parkName: "Camden State Park",
    state: "Minnesota",
    stateCode: "MN",
    latitude: 44.3711,
    longitude: -95.0978,
    address: "1897 Camden Park Road, Lynd, MN 56157",
    phone: "507-872-7031",
    email: "camden.statepark@state.mn.us",
    reservationUrl: "https://www.dnr.state.mn.us/state_parks/track-chairs.html",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "campground"],
    mapUrl: "https://maps.google.com/?q=Camden+State+Park+MN",
  },
  {
    id: "mn-crow-wing",
    parkName: "Crow Wing State Park",
    state: "Minnesota",
    stateCode: "MN",
    latitude: 46.2694,
    longitude: -94.3461,
    address: "3124 State Park Road, Brainerd, MN 56401",
    phone: "218-825-3075",
    email: "crowwing.statepark@state.mn.us",
    reservationUrl: "https://www.dnr.state.mn.us/state_parks/track-chairs.html",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "campground"],
    mapUrl: "https://maps.google.com/?q=Crow+Wing+State+Park+MN",
  },
  {
    id: "mn-maplewood",
    parkName: "Maplewood State Park",
    state: "Minnesota",
    stateCode: "MN",
    latitude: 45.0144,
    longitude: -92.8419,
    address: "39721 Park Entrance Road, Pelican Rapids, MN 56572",
    phone: "218-863-8383",
    email: "maplewood.statepark@state.mn.us",
    reservationUrl: "https://www.dnr.state.mn.us/state_parks/track-chairs.html",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "campground"],
    mapUrl: "https://maps.google.com/?q=Maplewood+State+Park+MN",
  },
  {
    id: "mn-blue-mounds",
    parkName: "Blue Mounds State Park",
    state: "Minnesota",
    stateCode: "MN",
    latitude: 43.7194,
    longitude: -96.1928,
    address: "1410 161st Street, Luverne, MN 56156",
    phone: "507-283-6050",
    email: "bluemounds.statepark@state.mn.us",
    reservationUrl: "https://www.dnr.state.mn.us/state_parks/track-chairs.html",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "prairie"],
    mapUrl: "https://maps.google.com/?q=Blue+Mounds+State+Park+MN",
  },
  {
    id: "mn-frontenac",
    parkName: "Frontenac State Park",
    state: "Minnesota",
    stateCode: "MN",
    latitude: 44.5189,
    longitude: -92.3472,
    address: "29223 County 28 Boulevard, Frontenac, MN 55026",
    phone: "651-299-3000",
    email: "frontenac.statepark@state.mn.us",
    reservationUrl: "https://www.dnr.state.mn.us/state_parks/track-chairs.html",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "bluffs"],
    mapUrl: "https://maps.google.com/?q=Frontenac+State+Park+MN",
  },
  {
    id: "mn-itasca",
    parkName: "Itasca State Park",
    state: "Minnesota",
    stateCode: "MN",
    latitude: 47.2372,
    longitude: -95.2081,
    address: "36750 Main Park Drive, Park Rapids, MN 56470",
    phone: "218-699-7251",
    email: "itasca.statepark@state.mn.us",
    reservationUrl: "https://www.dnr.state.mn.us/state_parks/track-chairs.html",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "campground", "lakeshore"],
    accessibleTrails: ["Headwaters Trail", "Wilderness Drive"],
    notes: "Home of the Mississippi River headwaters",
    mapUrl: "https://maps.google.com/?q=Itasca+State+Park+MN",
  },
  {
    id: "mn-split-rock",
    parkName: "Split Rock Lighthouse State Park",
    state: "Minnesota",
    stateCode: "MN",
    latitude: 47.1994,
    longitude: -91.3672,
    phone: "218-595-7625",
    reservationUrl: "https://www.dnr.state.mn.us/state_parks/track-chairs.html",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "lakeshore"],
    accessibleTrails: ["Lake Superior shoreline"],
    mapUrl: "https://maps.google.com/?q=Split+Rock+Lighthouse+State+Park+MN",
  },
  {
    id: "mn-lake-bemidji",
    parkName: "Lake Bemidji State Park",
    state: "Minnesota",
    stateCode: "MN",
    latitude: 47.4994,
    longitude: -94.8267,
    phone: "218-308-2300",
    reservationUrl: "https://www.dnr.state.mn.us/state_parks/track-chairs.html",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "lakeshore", "campground"],
    mapUrl: "https://maps.google.com/?q=Lake+Bemidji+State+Park+MN",
  },
  // ===== MICHIGAN (32 locations) =====
  {
    id: "mi-bald-mountain",
    parkName: "Bald Mountain Recreation Area",
    state: "Michigan",
    stateCode: "MI",
    latitude: 42.7678,
    longitude: -83.1917,
    address: "1330 E. Greenshield Road, Lake Orion, MI",
    phone: "248-693-6767",
    reservationUrl: "https://www.michigan.gov/dnr/about/accessibility/track-chairs",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "2 hours",
    availability: "Daily 8am-4:30pm",
    terrainTypes: ["trails", "beach", "campground"],
    accessibleTrails: ["Rathburg Trail"],
    mapUrl: "https://maps.google.com/?q=Bald+Mountain+Recreation+Area+MI",
  },
  {
    id: "mi-grand-haven",
    parkName: "Grand Haven State Park",
    state: "Michigan",
    stateCode: "MI",
    latitude: 43.0564,
    longitude: -86.2206,
    phone: "616-399-9390",
    email: "DNR-PRD-GrandHavenSP@Michigan.gov",
    reservationUrl: "https://www.michigan.gov/dnr/about/accessibility/track-chairs",
    chairCount: 3,
    chairType: "Action Trackchair + Freedom Trax",
    cost: "Free",
    reservationMethod: "Online form",
    advanceNotice: "24 hours",
    maxDuration: "2 hours",
    availability: "May 1 - Oct 31, 9am-4pm",
    terrainTypes: ["beach"],
    notes: "3 chairs available - 2 Action Trackchairs + 1 Freedom Trax",
    mapUrl: "https://maps.google.com/?q=Grand+Haven+State+Park+MI",
  },
  {
    id: "mi-ludington",
    parkName: "Ludington State Park",
    state: "Michigan",
    stateCode: "MI",
    latitude: 43.8978,
    longitude: -86.5086,
    phone: "231-843-2423",
    reservationUrl: "https://www.michigan.gov/dnr/about/accessibility/track-chairs",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "beach", "campground"],
    accessibleTrails: ["Big Sable River beach area"],
    mapUrl: "https://maps.google.com/?q=Ludington+State+Park+MI",
  },
  {
    id: "mi-tahquamenon",
    parkName: "Tahquamenon Falls State Park",
    state: "Michigan",
    stateCode: "MI",
    latitude: 46.5972,
    longitude: -85.2178,
    phone: "906-492-3415",
    email: "DNR-TFalls@Michigan.gov",
    reservationUrl: "https://www.michigan.gov/dnr/about/accessibility/track-chairs",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call or email",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "campground"],
    accessibleTrails: ["Upper Falls viewing area", "North Country Trail"],
    notes: "Access to view the famous Upper and Lower Falls",
    mapUrl: "https://maps.google.com/?q=Tahquamenon+Falls+State+Park+MI",
  },
  {
    id: "mi-holland",
    parkName: "Holland State Park",
    state: "Michigan",
    stateCode: "MI",
    latitude: 42.7731,
    longitude: -86.2006,
    phone: "616-399-9390",
    reservationUrl: "https://www.michigan.gov/dnr/about/accessibility/track-chairs",
    chairCount: 2,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "2 hours",
    availability: "Memorial Day - Labor Day, Mon-Fri 9am-3pm",
    terrainTypes: ["beach"],
    mapUrl: "https://maps.google.com/?q=Holland+State+Park+MI",
  },
  {
    id: "mi-sleeping-bear",
    parkName: "Sleeping Bear Dunes National Lakeshore",
    state: "Michigan",
    stateCode: "MI",
    latitude: 44.8678,
    longitude: -86.0489,
    phone: "231-326-4700",
    chairCount: 1,
    chairType: "Beach Wheelchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "Full day",
    availability: "Summer season",
    terrainTypes: ["beach", "dunes"],
    mapUrl: "https://maps.google.com/?q=Sleeping+Bear+Dunes+National+Lakeshore+MI",
  },
  {
    id: "mi-warren-dunes",
    parkName: "Warren Dunes State Park",
    state: "Michigan",
    stateCode: "MI",
    latitude: 41.9078,
    longitude: -86.5953,
    phone: "269-426-4013",
    reservationUrl: "https://www.michigan.gov/dnr/about/accessibility/track-chairs",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "2 hours",
    availability: "Year-round",
    terrainTypes: ["beach", "trails", "dunes"],
    mapUrl: "https://maps.google.com/?q=Warren+Dunes+State+Park+MI",
  },
  {
    id: "mi-petoskey",
    parkName: "Petoskey State Park",
    state: "Michigan",
    stateCode: "MI",
    latitude: 45.3756,
    longitude: -84.9553,
    phone: "231-347-2311",
    reservationUrl: "https://www.michigan.gov/dnr/about/accessibility/track-chairs",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "2 hours",
    availability: "Year-round",
    terrainTypes: ["beach", "trails"],
    mapUrl: "https://maps.google.com/?q=Petoskey+State+Park+MI",
  },
  // ===== TENNESSEE (select highlights - 32 parks total) =====
  {
    id: "tn-fall-creek",
    parkName: "Fall Creek Falls State Park",
    state: "Tennessee",
    stateCode: "TN",
    latitude: 36.3667,
    longitude: -85.3556,
    region: "Middle TN",
    phone: "423-881-5298",
    reservationUrl: "https://tnstateparks.com/accessibility/all-terrain-wheelchairs",
    chairCount: 1,
    chairType: "All-Terrain Wheelchair",
    cost: "Free",
    reservationMethod: "Online",
    advanceNotice: "Advance notice recommended",
    maxDuration: "Full day",
    availability: "Year-round",
    terrainTypes: ["trails", "campground"],
    accessibleTrails: ["Gorge Overlook Trail", "Nature Trail"],
    notes: "Tennessee's largest state park with 256-foot waterfall",
    mapUrl: "https://maps.google.com/?q=Fall+Creek+Falls+State+Park+TN",
  },
  {
    id: "tn-radnor-lake",
    parkName: "Radnor Lake State Park",
    state: "Tennessee",
    stateCode: "TN",
    latitude: 36.0639,
    longitude: -86.8094,
    region: "Middle TN",
    phone: "615-373-3467",
    reservationUrl: "https://tnstateparks.com/accessibility/all-terrain-wheelchairs",
    chairCount: 1,
    chairType: "All-Terrain Wheelchair",
    cost: "Free",
    reservationMethod: "Online",
    advanceNotice: "Advance notice recommended",
    maxDuration: "Full day",
    availability: "Year-round",
    terrainTypes: ["trails", "lakeshore"],
    accessibleTrails: ["Lake Trail"],
    notes: "Nashville's premier nature area",
    mapUrl: "https://maps.google.com/?q=Radnor+Lake+State+Park+TN",
  },
  {
    id: "tn-warriors-path",
    parkName: "Warriors' Path State Park",
    state: "Tennessee",
    stateCode: "TN",
    latitude: 36.5367,
    longitude: -82.5689,
    region: "East TN",
    phone: "423-239-8531",
    reservationUrl: "https://tnstateparks.com/accessibility/all-terrain-wheelchairs",
    chairCount: 1,
    chairType: "All-Terrain Wheelchair",
    cost: "Free",
    reservationMethod: "Online",
    advanceNotice: "Advance notice recommended",
    maxDuration: "Full day",
    availability: "Year-round",
    terrainTypes: ["trails", "lakeshore", "campground"],
    mapUrl: "https://maps.google.com/?q=Warriors+Path+State+Park+TN",
  },
  {
    id: "tn-cummins-falls",
    parkName: "Cummins Falls State Park",
    state: "Tennessee",
    stateCode: "TN",
    latitude: 36.25,
    longitude: -85.5833,
    region: "Middle TN",
    phone: "931-268-2471",
    reservationUrl: "https://tnstateparks.com/accessibility/all-terrain-wheelchairs",
    chairCount: 1,
    chairType: "All-Terrain Wheelchair",
    cost: "Free",
    reservationMethod: "Online",
    advanceNotice: "Advance notice recommended",
    maxDuration: "Full day",
    availability: "Year-round",
    terrainTypes: ["trails"],
    notes: "75-foot cascading waterfall",
    mapUrl: "https://maps.google.com/?q=Cummins+Falls+State+Park+TN",
  },
  // ===== GEORGIA (select highlights - 17 parks total) =====
  {
    id: "ga-cloudland-canyon",
    parkName: "Cloudland Canyon State Park",
    state: "Georgia",
    stateCode: "GA",
    latitude: 34.8367,
    longitude: -85.4817,
    address: "122 Cloudland Canyon Park Rd, Rising Fawn, GA 30738",
    phone: "706-657-4050",
    reservationUrl: "https://www.allterraingeorgia.org/reserve",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free (certification required)",
    reservationMethod: "Online via All-Terrain Georgia",
    advanceNotice: "Advance reservation required",
    maxDuration: "Full day",
    availability: "Year-round",
    terrainTypes: ["trails", "campground"],
    accessibleTrails: ["West Rim Trail overlooks"],
    notes: "Spectacular canyon views. Certification via allterraingeorgia.org required.",
    mapUrl: "https://maps.google.com/?q=Cloudland+Canyon+State+Park+GA",
  },
  {
    id: "ga-sweetwater-creek",
    parkName: "Sweetwater Creek State Park",
    state: "Georgia",
    stateCode: "GA",
    latitude: 33.7572,
    longitude: -84.6289,
    phone: "770-732-5871",
    reservationUrl: "https://www.allterraingeorgia.org/reserve",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free (certification required)",
    reservationMethod: "Online via All-Terrain Georgia",
    advanceNotice: "Advance reservation required",
    maxDuration: "Full day",
    availability: "Year-round",
    terrainTypes: ["trails", "creek"],
    mapUrl: "https://maps.google.com/?q=Sweetwater+Creek+State+Park+GA",
  },
  {
    id: "ga-skidaway",
    parkName: "Skidaway Island State Park",
    state: "Georgia",
    stateCode: "GA",
    latitude: 31.9489,
    longitude: -81.0561,
    phone: "912-598-2300",
    reservationUrl: "https://www.allterraingeorgia.org/reserve",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free (certification required)",
    reservationMethod: "Online via All-Terrain Georgia",
    advanceNotice: "Advance reservation required",
    maxDuration: "Full day",
    availability: "Year-round",
    terrainTypes: ["trails", "marsh"],
    notes: "Near Savannah, coastal marsh trails",
    mapUrl: "https://maps.google.com/?q=Skidaway+Island+State+Park+GA",
  },
  // ===== LOUISIANA (7 locations) =====
  {
    id: "la-jimmie-davis",
    parkName: "Jimmie Davis State Park",
    state: "Louisiana",
    stateCode: "LA",
    latitude: 32.0833,
    longitude: -92.6333,
    phone: "318-249-2595",
    email: "jimmiedavis@crt.la.gov",
    reservationUrl: "https://thetrackchair.com/finder/",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "lakeshore"],
    mapUrl: "https://maps.google.com/?q=Jimmie+Davis+State+Park+LA",
  },
  {
    id: "la-sam-houston",
    parkName: "Sam Houston Jones State Park",
    state: "Louisiana",
    stateCode: "LA",
    latitude: 30.6333,
    longitude: -93.5667,
    phone: "337-855-2665",
    email: "samhouston@crt.la.gov",
    reservationUrl: "https://thetrackchair.com/finder/",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "campground"],
    mapUrl: "https://maps.google.com/?q=Sam+Houston+Jones+State+Park+LA",
  },
  {
    id: "la-bogue-chitto",
    parkName: "Bogue Chitto State Park",
    state: "Louisiana",
    stateCode: "LA",
    latitude: 30.7833,
    longitude: -90.25,
    phone: "985-839-5707",
    email: "boguechitto@crt.la.gov",
    reservationUrl: "https://thetrackchair.com/finder/",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or call",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "campground"],
    mapUrl: "https://maps.google.com/?q=Bogue+Chitto+State+Park+LA",
  },
  // ===== SOUTH DAKOTA (3 locations) =====
  {
    id: "sd-custer",
    parkName: "Custer State Park",
    state: "South Dakota",
    stateCode: "SD",
    latitude: 43.7628,
    longitude: -103.4439,
    phone: "605-394-2693",
    email: "custerstatepark@state.sd.us",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "prairie", "campground"],
    accessibleTrails: ["Wildlife Loop Road trails"],
    notes: "See bison, pronghorn, and wild burros from the track chair",
    mapUrl: "https://maps.google.com/?q=Custer+State+Park+SD",
  },
  // ===== NORTH DAKOTA (4 locations) =====
  {
    id: "nd-lake-sakakawea",
    parkName: "Lake Sakakawea State Park",
    state: "North Dakota",
    stateCode: "ND",
    latitude: 47.5167,
    longitude: -101.4167,
    address: "720 Park Ave, Pick City, ND 58545",
    phone: "701-487-3315",
    email: "lssp@nd.gov",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "lakeshore"],
    mapUrl: "https://maps.google.com/?q=Lake+Sakakawea+State+Park+ND",
  },
  // ===== COLORADO (3 locations) =====
  {
    id: "co-staunton",
    parkName: "Staunton State Park",
    state: "Colorado",
    stateCode: "CO",
    latitude: 39.5167,
    longitude: -105.3667,
    phone: "303-838-7975",
    email: "trackchair@state.co.us",
    reservationUrl: "https://thetrackchair.com/finder/",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online or email",
    advanceNotice: "48 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "mountain"],
    accessibleTrails: ["Elk Falls Trail", "Chase Meadow Trail"],
    notes: "Pioneer of Colorado's track chair program. Mountain terrain at 8,100 ft elevation.",
    mapUrl: "https://maps.google.com/?q=Staunton+State+Park+CO",
  },
  // ===== WISCONSIN =====
  {
    id: "wi-peninsula",
    parkName: "Peninsula State Park",
    state: "Wisconsin",
    stateCode: "WI",
    latitude: 45.15,
    longitude: -87.2167,
    phone: "920-868-3258",
    reservationUrl: "https://peninsulastatepark.org/reserve-our-track-chair/",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Online",
    advanceNotice: "Advance reservation recommended",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "beach", "campground"],
    accessibleTrails: ["Sunset Trail", "Eagle Trail overlook"],
    notes: "Door County's most popular state park",
    mapUrl: "https://maps.google.com/?q=Peninsula+State+Park+WI",
  },
  // ===== TEXAS (10 locations) =====
  {
    id: "tx-palo-duro",
    parkName: "Palo Duro Canyon State Park",
    state: "Texas",
    stateCode: "TX",
    latitude: 34.9333,
    longitude: -101.6667,
    phone: "806-488-2227",
    reservationUrl: "https://tpwd.texas.gov/state-parks/park-information/accessibility/assistive-chairs",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call park",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "canyon"],
    notes: "Second-largest canyon in the US",
    mapUrl: "https://maps.google.com/?q=Palo+Duro+Canyon+State+Park+TX",
  },
  {
    id: "tx-hueco-tanks",
    parkName: "Hueco Tanks State Park",
    state: "Texas",
    stateCode: "TX",
    latitude: 31.9167,
    longitude: -106.05,
    phone: "915-857-1135",
    reservationUrl: "https://tpwd.texas.gov/state-parks/park-information/accessibility/assistive-chairs",
    chairCount: 1,
    chairType: "All-Terrain Wheelchair",
    cost: "Free",
    reservationMethod: "Call park",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "desert"],
    notes: "Near El Paso, ancient rock art site",
    mapUrl: "https://maps.google.com/?q=Hueco+Tanks+State+Park+TX",
  },
  // ===== OHIO =====
  {
    id: "oh-oak-openings",
    parkName: "Oak Openings Preserve (Metroparks Toledo)",
    state: "Ohio",
    stateCode: "OH",
    latitude: 41.55,
    longitude: -83.85,
    phone: "419-407-9700",
    reservationUrl: "https://metroparkstoledo.com/recreation-equipment-catalog/recreation-equipment-catalog/action-track-chair/",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free (Reeve Foundation Grant)",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "prairie"],
    mapUrl: "https://maps.google.com/?q=Oak+Openings+Preserve+Metropark+OH",
  },
  // ===== WASHINGTON =====
  {
    id: "wa-lake-sammamish",
    parkName: "Lake Sammamish State Park",
    state: "Washington",
    stateCode: "WA",
    latitude: 47.5917,
    longitude: -122.0667,
    phone: "425-649-4275",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Spring-Fall (rotates to Riverside SP in winter)",
    terrainTypes: ["trails", "beach", "lakeshore"],
    mapUrl: "https://maps.google.com/?q=Lake+Sammamish+State+Park+WA",
  },
  // ===== MONTANA =====
  {
    id: "mt-lake-elmo",
    parkName: "Lake Elmo State Park",
    state: "Montana",
    stateCode: "MT",
    latitude: 45.8167,
    longitude: -108.0167,
    phone: "406-247-2955",
    email: "Emily.Tyler@mt.gov",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call or email",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "lakeshore"],
    mapUrl: "https://maps.google.com/?q=Lake+Elmo+State+Park+MT",
  },
  // ===== WYOMING =====
  {
    id: "wy-bear-river",
    parkName: "Bear River State Park",
    state: "Wyoming",
    stateCode: "WY",
    latitude: 41.0333,
    longitude: -110.9667,
    phone: "307-789-6547",
    chairCount: 1,
    chairType: "Action Trackchair",
    cost: "Free",
    reservationMethod: "Call ahead",
    advanceNotice: "24 hours",
    maxDuration: "3 hours",
    availability: "Year-round",
    terrainTypes: ["trails", "prairie"],
    notes: "Funded by Ford Bronco Wild Fund grant",
    mapUrl: "https://maps.google.com/?q=Bear+River+State+Park+WY",
  },
  // ===== NATIONAL PARKS =====
  {
    id: "nps-yellowstone",
    parkName: "Yellowstone National Park",
    state: "Wyoming",
    stateCode: "WY",
    latitude: 44.428,
    longitude: -110.5885,
    phone: "307-344-7381",
    reservationUrl: "https://www.nps.gov/yell/planyourvisit/accessibility.htm",
    chairCount: 2,
    chairType: "Beach Wheelchair / All-Terrain",
    cost: "Free",
    reservationMethod: "Call visitor center",
    advanceNotice: "24 hours",
    maxDuration: "Full day",
    availability: "Summer season (May-Oct)",
    terrainTypes: ["trails", "boardwalks"],
    accessibleTrails: ["Old Faithful boardwalk", "Mammoth Hot Springs"],
    notes: "Limited availability, popular demand",
    mapUrl: "https://maps.google.com/?q=Yellowstone+National+Park",
  },
  {
    id: "nps-grand-canyon",
    parkName: "Grand Canyon National Park",
    state: "Arizona",
    stateCode: "AZ",
    latitude: 36.0544,
    longitude: -112.1401,
    phone: "928-638-7888",
    reservationUrl: "https://www.nps.gov/grca/planyourvisit/accessibility.htm",
    chairCount: 1,
    chairType: "All-Terrain Wheelchair",
    cost: "Free",
    reservationMethod: "Call visitor center",
    advanceNotice: "24 hours",
    maxDuration: "Full day",
    availability: "Year-round",
    terrainTypes: ["trails", "rim"],
    accessibleTrails: ["Rim Trail (paved sections)"],
    mapUrl: "https://maps.google.com/?q=Grand+Canyon+National+Park",
  },
  {
    id: "nps-acadia",
    parkName: "Acadia National Park",
    state: "Maine",
    stateCode: "ME",
    latitude: 44.3386,
    longitude: -68.2733,
    phone: "207-288-3338",
    reservationUrl: "https://www.nps.gov/acad/planyourvisit/accessibility.htm",
    chairCount: 1,
    chairType: "Beach Wheelchair",
    cost: "Free",
    reservationMethod: "Call visitor center",
    advanceNotice: "24 hours",
    maxDuration: "Full day",
    availability: "Summer season",
    terrainTypes: ["beach", "trails"],
    accessibleTrails: ["Sand Beach", "Carriage Roads"],
    mapUrl: "https://maps.google.com/?q=Acadia+National+Park+ME",
  },
  {
    id: "nps-glacier",
    parkName: "Glacier National Park",
    state: "Montana",
    stateCode: "MT",
    latitude: 48.7596,
    longitude: -113.787,
    phone: "406-888-7800",
    reservationUrl: "https://www.nps.gov/glac/planyourvisit/accessibility.htm",
    chairCount: 1,
    chairType: "All-Terrain Wheelchair",
    cost: "Free",
    reservationMethod: "Call visitor center",
    advanceNotice: "24 hours",
    maxDuration: "Full day",
    availability: "Summer season (June-Sept)",
    terrainTypes: ["trails"],
    accessibleTrails: ["Trail of the Cedars", "Apgar area trails"],
    mapUrl: "https://maps.google.com/?q=Glacier+National+Park+MT",
  },
];

// Summary stats
export const TRACK_CHAIR_SUMMARY = {
  totalStates: 17,
  totalLocations: 150, // approximate across all programs
  totalChairs: 170,
  allFree: true,
  topStates: ["Tennessee (32)", "Michigan (32)", "Minnesota (17)", "Georgia (17)", "Texas (10)"],
  keyFacts: [
    "All track chairs are FREE to use at state and national parks",
    "Reservations recommended — call 24 hours ahead or book online",
    "Chairs handle trails, sand, mud, snow, and up to 8 inches of water",
    "Most support up to 300 lbs with 6-8 hour battery life",
    "Companion/caregiver may be required at some locations",
    "Many programs funded by Ford Bronco Wild Fund and community donations",
  ],
};
